# Docker Compose sonarr
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    restart: unless-stopped # Updated restart policy for more control
    labels:
      - all=true

    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${DockerDir}/sonarr:/config
      - ${MediaDir}/video/tv-shows:/tv
      - ${MediaDir}/downloads/complete:/downloads
    ports:
      - 8989:8989
    networks:
      backend:
        aliases:
          - sonarr
    depends_on:
      - sabnzdb
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8989 || exit 1"] # Modified to use "localhost" within the container
      interval: 1m
      timeout: 10s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

