name: app1

# Include all services relevant to app1
include:
  - ../../services/docker-compose.autoheal.yml
  - ../../services/docker-compose.nginx.yml
  - ../../services/docker-compose.homepage.yml


# Define stack-specific network
networks:
  backend:
    driver: bridge

# No docker_sock volume here â€“ services will bind mount it directly
volumes: {}

