name: iotapp1

# Include all services relevant to iotapp1
include:
  - ../../services/docker-compose.autoheal.yml
  - ../../services/docker-compose.sabnzbd.yml
  - ../../services/docker-compose.radarr.yml
  - ../../services/docker-compose.sonarr.yml
  - ../../services/docker-compose.bazarr.yml

# Define stack-specific network
networks:
  backend:
    driver: bridge

# No stack-level volumes needed â€“ services bind mount docker.sock directly
volumes: {}